# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

analyzer:
  errors:
    use_super_parameters: ignore
    deprecated_member_use: ignore
    duplicate_import: ignore
    avoid_print: ignore
    constant_identifier_names: ignore
    use_build_context_synchronously: ignore
    unnecessary_to_list_in_spreads: ignore
    prefer_final_fields: ignore
    unused_import: ignore
    unused_field: ignore
    non_constant_identifier_names: ignore
    empty_statements: ignore
    unnecessary_import: ignore
    unused_local_variable: ignore
    unnecessary_brace_in_string_interps: ignore
    unused_element: ignore
    
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Uncomment to disable specific rules
    # avoid_print: false
    # prefer_single_quotes: true